apiVersion: v1
kind: ConfigMap
metadata:
  name: central-hub-config
  labels:
      app: central-hub
data:
  default.json: |
    {
      "PORT": "4001",
      "HOSTNAME": "http://central-hub.local",
      "API_URL": "http://central-ledger:3000",
      "ADMIN_API_URL": "http://central-ledger:3001"
    }
