---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
    name: central-hub-deployment
    labels:
      app: central-hub
 spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: central-hub
      spec:
        containers:
          - name: central-hub
            image: mojaloop/central-hub:latest
            ports:
              - containerPort: 4001
            livenessProbe:
              httpGet:
                path: /health
                port: 4001
              initialDelaySeconds: 30
              periodSeconds: 10
            volumeMounts:
            - name: config-volume
              mountPath: /opt/central-hub/config
        volumes:
          - name: config-volume
            configMap:
              name: central-hub-config
              items:
              - key: default.json
                path: default.json
